### ISSUE TITLE
issue  when compile matcaffe

### ISSUE THREAD

**Issue by carrierlxk** [unsky/Deformable-ConvNets-caffe#1]
Hi, when I compile the matcaffe, I face an issue: 

/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:45:40: error: template argument 1 is invalid
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:45:40: error: template argument 2 is invalid
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:45:50: error: invalid type in declaration before ‘;’ token
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:46:37: error: template argument 1 is invalid
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:46:37: error: template argument 2 is invalid
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:46:44: error: invalid type in declaration before ‘;’ token
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:174:66: error: template argument 1 is invalid
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:174:66: error: template argument 2 is invalid
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp: In function ‘mxArray* ptr_vec_to_handle_vec(const int&)’:
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:175:57: error: request for member ‘size’ in ‘ptr_vec’, which is of non-class type ‘const int’
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:176:31: error: request for member ‘size’ in ‘ptr_vec’, which is of non-class type ‘const int’
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:177:27: error: invalid types ‘const int[int]’ for array subscript
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp: In function ‘void get_solver(int, mxArray**, int, const mxArray**)’:
/home/lxk/code/tracking/Deformable-ConvNets/matlab/+caffe/private/caffe_.cpp:193:3: error: reference to ‘shared_ptr’ is ambiguous

Could you tell me the solution? Thank you.

**Comment by unsky** [comment]
sorry,because i have to do my other works, i only complete the forwad part  in deformable conv net.  but if you have interesting to complete it, you can fork it. BY THE WAY, the core codes is completed in deformable_im2col.cu, good lunck.
ps: i tink you should compile it using c++11,good luck.

**Comment by carrierlxk** [comment]
Thank you@unsky. I think the reason maybe the version of g++.

**Comment by ym547559398** [comment]
i have added the deformable convnet to our caffe:"https://github.com/soeaver/py-RFCN-priv" and compiled through. However, this can not use the deformable convolution to train a network and i have no idea about the back part, could you give some help?
