### ISSUE TITLE
F1229 20:40:19.387852 106942 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: DeformableConvolution

### ISSUE THREAD

**Issue by fujihuang** [unsky/Deformable-ConvNets-caffe#12]
Hi, 
  Thanks for your sharing. I try to use the codes in my caffe, adding all the words you mentioned in Readme, unfortunately, when i run the LeNet network, it failed and encounter the error as the title, I have tried many times, still failed... when i make your caffe, and run the LeNet network, it worked. Now, i am very confused, could you give me some advise? I will be very appreciate it.

**Comment by beniz** [comment]
You need to modify layer_factory.cpp to register the DeformableConvolution.

**Comment by fujihuang** [comment]
emmm... yes, it works, thank you very much!!!
