### ISSUE TITLE
How about the baseline of faster rcnn without Deformable_CNN

### ISSUE THREAD

**Issue by fujihuang** [unsky/Deformable-ConvNets-caffe#13]
Hi,
  As you posted in ReadMe: when using Deformable_CNN, it get 78.1 on VOC 2007 test set, I am wondering the results without Deformabel_CNN, whether you could post publicly for clear comparison
Best

**Comment by unsky** [comment]
about 76~77, do it by yourdelf.

**Comment by fujihuang** [comment]
Thanks~~
