### ISSUE TITLE
How much deformable convolution we need?

### ISSUE THREAD

**Issue by hangkaitan** [unsky/Deformable-ConvNets-caffe#14]
Hi,
    we just need add little deformable convolution at the end of the net?

**Comment by unsky** [comment]
Well, it all depend on the situation. i think.

**Comment by feitiandemiaomi** [comment]
@unsky  理论上，可变层可以放到任意位置吧，但是我想像前几层那种特征，诸如纹理，边缘信息的，设置可变层又没有意义，所以我想问一下，是否一般放到提取抽象特征的位置，比如中间或者靠后的网络层？
