### ISSUE TITLE
the error after  make 

### ISSUE THREAD

**Issue by feitiandemiaomi** [unsky/Deformable-ConvNets-caffe#17]
Creating symlink /home/songzhao/code/Deformable-ConvNets-caffe/caffe/python/caffe/_caffe.so -> /home/songzhao/code/Deformable-ConvNets-caffe/caffe/build/lib/_caffe.so
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cv::String::allocate(unsigned long)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cv::imread(cv::String const&, int)'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cv::String::deallocate()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `cv::imencode(cv::String const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
tools/CMakeFiles/upgrade_net_proto_binary.dir/build.make:134: recipe for target 'tools/upgrade_net_proto_binary' failed
make[2]: *** [tools/upgrade_net_proto_binary] Error 1
CMakeFiles/Makefile2:663: recipe for target 'tools/CMakeFiles/upgrade_net_proto_binary.dir/all' failed
make[1]: *** [tools/CMakeFiles/upgrade_net_proto_binary.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 93%] Built target pycaffe

Hi, thank your work , but I met an error when I compiled , the route of opencv is correct and there are not error  if compiling commonly , Did you meet it once?

**Comment by unsky** [comment]
@feitiandemiaomi  use cmake in readme . the install is same to the office caffe,

**Comment by feitiandemiaomi** [comment]
Thanks your quick reply , I used cmake in readme ,but the error  seems  to have something to do with the version of opencv

**Comment by unsky** [comment]
the install is same to the office caffe， if you have error in install , just google it.

**Comment by feitiandemiaomi** [comment]
ok , I try it
