### ISSUE TITLE
train lenet那里有几个问题

### ISSUE THREAD

**Issue by zhanglonghao1992** [unsky/Deformable-ConvNets-caffe#4]
1.既然offset的输出是72那后面的dec卷积是不是应该带group=4呢？为什么要用group卷积呢？
2.为什么输入dec的feature map是conv1的不是pool1的呢？做了pooling之后尺寸不是对不上了吗？

**Comment by unsky** [comment]
抱歉，整理代码一时仓促连错了，我会更新readme解释group

**Comment by zhanglonghao1992** [comment]
@unsky 嗯！感谢~

**Comment by unsky** [comment]
更新了deformable group,加入了尺寸检测代码。连接不对会报错。

**Comment by foralliance** [comment]
今天用你的代码，发现在caffe.proto中的定义的是group，但是在lenet_train_test.prototxt中写deformable_convolution_param时，用的确是defomable_group．
应该是一个疏忽．

**Comment by zhanglonghao1992** [comment]
@unsky 在deformable_conv_layer.cu的25行，调用deformable_im2col_gpu函数的时候传了两个参数bottom[0]->shape(1)和bottom[0]->shape(0)，但是deformable_im2col_gpu中该位置需要传入的是height和width，这里是不是有点问题

**Comment by unsky** [comment]
@zhanglonghao1992  感谢你的指出，我在前面的测试中也发现了这个错误，这个错误是个很严重的错误，最新上传已经修正，这错误也会导致在一些情况下gpu指针崩溃。感谢。

**Comment by zhanglonghao1992** [comment]
@unsky 嗯没事的~

**Comment by zhanglonghao1992** [comment]
@unsky 没见到最新上传啊。。

**Comment by unsky** [comment]
@zhanglonghao1992 更新了，忙毕业忘了

**Comment by zhanglonghao1992** [comment]
@unsky haha 好吧
