### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by yemika** [unsky/Deformable-ConvNets-caffe#5]
感谢您的分享，有一些存疑的地方。
按照给出的脚本训练测试，准确率在10%，10000次的迭代，训练显示loss一直维持在87左右并不能收敛。
其次给出的offset的channel与defconv的group是如何对应的，这部分有点迷惑。

**Comment by unsky** [comment]
batch 为1 的检测训练还是需要很多注意的地方，尤其是batchnorm和scale方面，我将更新我的最新实验结果。

**Comment by unsky** [comment]
@yemika  使用最新代码
