### ISSUE TITLE
I got compile error

### ISSUE THREAD

**Issue by hangil55** [unsky/Deformable-ConvNets-caffe#8]
I got message saying that
src/caffe/layers/deformable_conv_layer.cpp:213:16: error: ‘const class caffe::DeformableConvolutionParameter’ has no member named ‘group’

I am using cuda 8.0 & cudnn 5.1

**Comment by unsky** [comment]
caffe.prototxt is right?

**Comment by unsky** [comment]
readme have some mistake, use caffe.protxt in deformable_conv_cxx

**Comment by hangil55** [comment]
I complete this issue. thanks
There are not exist  "optional uint32 group = 5 [default = 1];" in deformable_conv_cxx.
(I added that line and make it compile)
Thank you
